# Generated by Django 3.2 on 2022-07-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcomeapp', '0002_rename_device_visitors'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='acompany',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='visitors',
            name='person',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='visitors',
            name='text1',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
