# Generated by Django 3.2 on 2022-07-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcomeapp', '0003_auto_20220713_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='Visit_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
