# Generated by Django 3.2 on 2022-07-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcomeapp', '0005_rename_visit_time_visitors_visit_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitors',
            old_name='visit_time',
            new_name='times',
        ),
        migrations.AddField(
            model_name='visitors',
            name='dates',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='visitors',
            name='tantousya',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
