# Generated by Django 3.2 on 2022-07-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcomeapp', '0006_auto_20220720_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='affair1',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='visitors',
            name='affair2',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
