# Generated by Django 3.2 on 2022-07-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcomeapp', '0007_auto_20220720_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='affair1',
            field=models.CharField(max_length=30),
        ),
    ]
