# Generated by Django 3.2 on 2022-07-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcomeapp', '0008_alter_visitors_affair1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitors',
            name='accompany',
        ),
        migrations.AddField(
            model_name='visitors',
            name='douhansya',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
