# Generated by Django 3.2 on 2022-07-20 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcomeapp', '0009_auto_20220720_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitors',
            old_name='douhansya',
            new_name='accompany',
        ),
    ]
