# Generated by Django 3.2 on 2022-07-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcomeapp', '0010_rename_douhansya_visitors_accompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='company',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='person_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
