# Generated by Django 3.2 on 2022-07-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcomeapp', '0011_auto_20220720_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitors',
            old_name='accompany',
            new_name='douhan',
        ),
        migrations.AddField(
            model_name='visitors',
            name='douhan1',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='visitors',
            name='douhan2',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
