# Generated by Django 3.2 on 2022-07-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcomeapp', '0013_auto_20220725_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='times',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
