# Generated by Django 3.2 on 2022-07-29 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('welcomeapp', '0015_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welcomeapp.account'),
        ),
    ]
